# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': 'https://puhazoli.github.io/asbe/',
                'doc_host': 'https://puhazoli.github.io',
                'git_url': 'https://github.com/puhazoli/asbe/tree/master',
                'lib_path': '.'},
  'syms': { 'asbe-master.asbe.base': {},
            'asbe-master.asbe.core': {},
            'asbe-master.asbe.estimators': {},
            'asbe-master.asbe.helper': {},
            'asbe-master.asbe.models': {},
            'asbe-master.build.lib.asbe.base': {},
            'asbe-master.build.lib.asbe.core': {},
            'asbe-master.build.lib.asbe.estimators': {},
            'asbe-master.build.lib.asbe.helper': {},
            'asbe-master.build.lib.asbe.models': {},
            'asbe-master.setup': {}}}
