# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FitTask": "00_base.ipynb",
         "BaseITEEstimator": "00_base.ipynb",
         "BaseActiveLearner": "00_base.ipynb",
         "BaseAcquisitionFunction": "00_base.ipynb",
         "BaseAssignmentFunction": "00_base.ipynb",
         "BaseStoppingRule": "00_base.ipynb",
         "RandomAcquisitionFunction": "01_core.ipynb",
         "UncertaintyAcquisitionFunction": "01_core.ipynb",
         "TypeSAcquistionFunction": "01_core.ipynb",
         "EMCMAcquisitionFunction": "01_core.ipynb",
         "RandomAssignmentFunction": "01_core.ipynb",
         "MajorityAssignmentFunction": "01_core.ipynb",
         "CausalForestEstimator": "estimators.ipynb",
         "OPENBTITEEstimator": "estimators.ipynb",
         "CEVAEEstimator": "estimators.ipynb"}

modules = ["base.py",
           "models.py",
           "estimators.py"]

doc_url = "https://puhazoli.github.io/asbe/"

git_url = "https://github.com/puhazoli/asbe/tree/master/"

def custom_doc_links(name): return None
