# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BaseITEEstimator": "00_base.ipynb",
         "BaseActiveLearner": "00_base.ipynb",
         "BaseAcquisitionFunction": "00_base.ipynb",
         "BaseAssignmentFunction": "00_base.ipynb",
         "random_batch_sampling": "01_core.ipynb",
         "uncertainty_batch_sampling": "01_core.ipynb",
         "type_s_batch_sampling": "01_core.ipynb",
         "expected_model_change_maximization": "01_core.ipynb",
         "ASLearner": "01_core.ipynb",
         "estimator_type": "01_core.ipynb",
         "ITEEstimator": "01_core.ipynb",
         "variance_based_assf": "01_core.ipynb"}

modules = ["base.py",
           "core.py"]

doc_url = "https://puhazoli.github.io/asbe/"

git_url = "https://github.com/puhazoli/asbe/tree/master/"

def custom_doc_links(name): return None
