baseurl: /asbe/
collections:
  tooltips:
    output: false
company_name: JADS
default_badges:
  colab: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    comments: true
    layout: page
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    comments: true
    layout: page
    search: true
    tooltip: true
description: ASBE
exclude:
- vendor
google_analytics: null
google_search: null
highlighter: rouge
host: 127.0.0.1
kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM
  math_engine: katex
  syntax_highlighter: rouge
markdown: kramdown
output: web
plugins:
- jekyll-remote-theme
port: 4000
remote_theme: fastai/nbdev-jekyll-theme
repository: puhazoli/asbe
sidebars:
- home_sidebar
site_title: ASBE
topnav_title: ASBE
twitter_username: zolipuha
use_math: true
